alt added
stzabiyaka/filmoteka-team-project pull request #48
Opened 2022-06-19 06:32 UTC by emsheremeta

2022-06-19 11:43 UTC, stzabiyaka requested changes

2022-06-19 11:43 UTC, stzabiyaka commented on src/js/modules/card-parser.js
> +    <h2 class="movie-card_title" alt = "title">${title}</h2>
тут титул не потрібний - прибирай

2022-06-19 11:43 UTC, stzabiyaka commented on src/js/modules/card-parser.js
>      <p class = "movie-card_genres">
тут потрібно `title ="Genres"` додати

2022-06-19 11:43 UTC, stzabiyaka commented on src/js/modules/card-parser.js
> +        <p class="movie-card_date" alt = "release_year">${release_date}</p>
тут  `title ="Release year"`, а не  alt = "release_year". альт для зображень

2022-06-19 11:43 UTC, stzabiyaka commented on src/js/modules/card-parser.js
> +        <p class="movie-card_avarage__accent" alt ="vote_average">${vote_average}</p>
тут  `title ="Vote average"`

2022-06-19 20:51 UTC, emsheremeta commented on src/js/modules/card-parser.js
> +    <h2 class="movie-card_title" alt = "title">${title}</h2>
done

2022-06-19 20:51 UTC, emsheremeta commented on src/js/modules/card-parser.js
>      <p class = "movie-card_genres">
done

2022-06-19 20:51 UTC, emsheremeta commented on src/js/modules/card-parser.js
> +        <p class="movie-card_date" alt = "release_year">${release_date}</p>
done

2022-06-19 20:51 UTC, emsheremeta commented on src/js/modules/card-parser.js
> +        <p class="movie-card_avarage__accent" alt ="vote_average">${vote_average}</p>
done

2022-06-20 15:19 UTC, stzabiyaka approved these changes

2022-06-20 15:19 UTC, merged